---
# prefix that need to be inserted before every command
prefix: r!

# list of user's ids with special permissions, only thrusted people
botOwners:
  - '212988300137463809' # MrBartusek

# on what hour replacements for next day (instead of today) will be fetched on !fetch
# set to false to disable
daySwitchHour: 16-00 # HH-MM

# all replacements that don't contain this string won't be shown
# replacementsFilter: '1'

# configuration for cron tasks
intervals:
  # how often will replacements channel be updated
  replacementsChannelsUpdate: 0 * * * *

# emoji that need to be detected in the replacements channel topic
replacementsChannelsTopicEmoji: "üóìÔ∏è"

# configuration for replacement fetchers
fetcherName: 'dummyFetcher'

fetchersConfiguration:
